#include <repo/ops/init.hpp>
#include <repo/repository.hpp>

#include <algorithm>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

namespace repo::ops {

// Forward declarations for template getter functions
namespace templates_internal {
auto get_cpp_template() -> std::string_view;
auto get_python_template() -> std::string_view;
auto get_javascript_template() -> std::string_view;
auto get_java_template() -> std::string_view;
auto get_go_template() -> std::string_view;
auto get_rust_template() -> std::string_view;
auto get_csharp_template() -> std::string_view;
auto get_ruby_template() -> std::string_view;
auto get_php_template() -> std::string_view;
auto get_swift_template() -> std::string_view;
auto get_kotlin_template() -> std::string_view;
auto get_cmake_template() -> std::string_view;
auto get_make_template() -> std::string_view;
auto get_vcpkg_template() -> std::string_view;
auto get_conan_template() -> std::string_view;
auto get_gradle_template() -> std::string_view;
auto get_maven_template() -> std::string_view;
auto get_macos_template() -> std::string_view;
auto get_linux_template() -> std::string_view;
auto get_windows_template() -> std::string_view;
auto get_vscode_template() -> std::string_view;
auto get_jetbrains_template() -> std::string_view;
auto get_vim_template() -> std::string_view;
} // namespace templates_internal

namespace {

// Get template content for a project type
auto get_template(ProjectType type) -> std::string_view {
    using namespace templates_internal;

    switch (type) {
        // Languages
        case ProjectType::Cpp:
            return get_cpp_template();
        case ProjectType::Python:
            return get_python_template();
        case ProjectType::JavaScript:
            return get_javascript_template();
        case ProjectType::Java:
            return get_java_template();
        case ProjectType::Go:
            return get_go_template();
        case ProjectType::Rust:
            return get_rust_template();
        case ProjectType::CSharp:
            return get_csharp_template();
        case ProjectType::Ruby:
            return get_ruby_template();
        case ProjectType::PHP:
            return get_php_template();
        case ProjectType::Swift:
            return get_swift_template();
        case ProjectType::Kotlin:
            return get_kotlin_template();

        // Build Systems
        case ProjectType::CMake:
            return get_cmake_template();
        case ProjectType::Make:
            return get_make_template();
        case ProjectType::Vcpkg:
            return get_vcpkg_template();
        case ProjectType::Conan:
            return get_conan_template();
        case ProjectType::Gradle:
            return get_gradle_template();
        case ProjectType::Maven:
            return get_maven_template();

        // Platforms
        case ProjectType::macOS:
            return get_macos_template();
        case ProjectType::Linux:
            return get_linux_template();
        case ProjectType::Windows:
            return get_windows_template();

        // Editors
        case ProjectType::VSCode:
            return get_vscode_template();
        case ProjectType::JetBrains:
            return get_jetbrains_template();
        case ProjectType::Vim:
            return get_vim_template();
    }

    return "";
}

// Create .gitignore file from templates
auto create_gitignore(const std::filesystem::path& repo_path, const std::vector<ProjectType>& types)
    -> Result<void> {
    if (types.empty()) {
        return {}; // No templates selected, success
    }

    auto gitignore_path = repo_path / ".gitignore";

    // Check if .gitignore already exists
    if (std::filesystem::exists(gitignore_path)) {
        // Don't modify existing file as per user requirement
        return {};
    }

    // Merge all templates
    std::ostringstream content;
    content << "# Generated by repo init\n";
    content << "# Created: " << std::chrono::system_clock::now() << "\n\n";

    for (const auto& type : types) {
        auto template_content = get_template(type);
        if (!template_content.empty()) {
            content << template_content << "\n";
        }
    }

    // Write to file
    std::ofstream file(gitignore_path);
    if (!file) {
        return std::unexpected(make_error(Error::Code::Unknown, "Failed to create .gitignore file",
                                          gitignore_path.string()));
    }

    file << content.str();

    if (!file) {
        return std::unexpected(make_error(Error::Code::Unknown, "Failed to write .gitignore file",
                                          gitignore_path.string()));
    }

    return {};
}

} // anonymous namespace

// Initialize a new Git repository
auto init(const InitParams& params) -> Result<InitResult> {
    // Initialize the repository using Repository::init()
    repo::InitOptions opts{.bare = params.bare};

    // Note: initial_branch_name is ignored for now as Repository::InitOptions doesn't support it
    // yet
    // TODO: Add initial_branch_name support to Repository::InitOptions in the future

    auto repo_result = Repository::init(params.path, opts);
    if (!repo_result.has_value()) {
        return std::unexpected(repo_result.error());
    }

    auto& repo = *repo_result;

    InitResult result{
        .git_dir = repo.git_dir(), .created_gitignore = false, .applied_templates = {}};

    // Create .gitignore if project types specified
    if (!params.project_types.empty()) {
        auto gitignore_result = create_gitignore(params.path, params.project_types);
        if (!gitignore_result.has_value()) {
            // .gitignore creation failed, but repo was created - continue
            // (We could optionally return the error here if strict behavior is desired)
        } else {
            result.created_gitignore = true;
            result.applied_templates = params.project_types;
        }
    }

    return result;
}

// Helper: Get human-readable name for project type
auto project_type_name(ProjectType type) -> std::string {
    switch (type) {
        // Languages
        case ProjectType::Cpp:
            return "C++";
        case ProjectType::Python:
            return "Python";
        case ProjectType::JavaScript:
            return "JavaScript/TypeScript (Node, React, Vue, Bun, Deno)";
        case ProjectType::Java:
            return "Java";
        case ProjectType::Go:
            return "Go";
        case ProjectType::Rust:
            return "Rust";
        case ProjectType::CSharp:
            return "C#";
        case ProjectType::Ruby:
            return "Ruby";
        case ProjectType::PHP:
            return "PHP";
        case ProjectType::Swift:
            return "Swift";
        case ProjectType::Kotlin:
            return "Kotlin";

        // Build Systems
        case ProjectType::CMake:
            return "CMake";
        case ProjectType::Make:
            return "Make";
        case ProjectType::Vcpkg:
            return "vcpkg";
        case ProjectType::Conan:
            return "Conan";
        case ProjectType::Gradle:
            return "Gradle";
        case ProjectType::Maven:
            return "Maven";

        // Platforms
        case ProjectType::macOS:
            return "macOS";
        case ProjectType::Linux:
            return "Linux";
        case ProjectType::Windows:
            return "Windows";

        // Editors
        case ProjectType::VSCode:
            return "VSCode";
        case ProjectType::JetBrains:
            return "JetBrains IDEs";
        case ProjectType::Vim:
            return "Vim";
    }

    return "Unknown";
}

// Helper: Get project type from string (for CLI parsing)
auto parse_project_type(const std::string& str) -> std::optional<ProjectType> {
    static const std::unordered_map<std::string, ProjectType> type_map = {
        // C++ aliases
        {"cpp", ProjectType::Cpp},
        {"c++", ProjectType::Cpp},
        {"cxx", ProjectType::Cpp},

        // Python aliases
        {"python", ProjectType::Python},
        {"py", ProjectType::Python},

        // JavaScript/TypeScript aliases
        {"javascript", ProjectType::JavaScript},
        {"js", ProjectType::JavaScript},
        {"typescript", ProjectType::JavaScript},
        {"ts", ProjectType::JavaScript},
        {"node", ProjectType::JavaScript},
        {"nodejs", ProjectType::JavaScript},
        {"react", ProjectType::JavaScript},
        {"vue", ProjectType::JavaScript},
        {"bun", ProjectType::JavaScript},
        {"deno", ProjectType::JavaScript},

        // Java aliases
        {"java", ProjectType::Java},

        // Go aliases
        {"go", ProjectType::Go},
        {"golang", ProjectType::Go},

        // Rust aliases
        {"rust", ProjectType::Rust},
        {"rs", ProjectType::Rust},

        // C# aliases
        {"csharp", ProjectType::CSharp},
        {"c#", ProjectType::CSharp},
        {"cs", ProjectType::CSharp},
        {"dotnet", ProjectType::CSharp},

        // Ruby aliases
        {"ruby", ProjectType::Ruby},
        {"rb", ProjectType::Ruby},

        // PHP aliases
        {"php", ProjectType::PHP},

        // Swift aliases
        {"swift", ProjectType::Swift},

        // Kotlin aliases
        {"kotlin", ProjectType::Kotlin},
        {"kt", ProjectType::Kotlin},

        // Build system aliases
        {"cmake", ProjectType::CMake},
        {"make", ProjectType::Make},
        {"makefile", ProjectType::Make},
        {"vcpkg", ProjectType::Vcpkg},
        {"conan", ProjectType::Conan},
        {"gradle", ProjectType::Gradle},
        {"maven", ProjectType::Maven},
        {"mvn", ProjectType::Maven},

        // Platform aliases
        {"macos", ProjectType::macOS},
        {"mac", ProjectType::macOS},
        {"osx", ProjectType::macOS},
        {"darwin", ProjectType::macOS},
        {"linux", ProjectType::Linux},
        {"windows", ProjectType::Windows},
        {"win", ProjectType::Windows},

        // Editor aliases
        {"vscode", ProjectType::VSCode},
        {"code", ProjectType::VSCode},
        {"jetbrains", ProjectType::JetBrains},
        {"idea", ProjectType::JetBrains},
        {"intellij", ProjectType::JetBrains},
        {"clion", ProjectType::JetBrains},
        {"pycharm", ProjectType::JetBrains},
        {"webstorm", ProjectType::JetBrains},
        {"vim", ProjectType::Vim},
        {"vi", ProjectType::Vim},
        {"neovim", ProjectType::Vim},
        {"nvim", ProjectType::Vim},
    };

    // Convert to lowercase for case-insensitive matching
    std::string lower_str = str;
    std::transform(lower_str.begin(), lower_str.end(), lower_str.begin(), ::tolower);

    auto it = type_map.find(lower_str);
    if (it != type_map.end()) {
        return it->second;
    }

    return std::nullopt;
}

// Helper: Get all available project types grouped by category
auto get_project_type_categories() -> std::vector<ProjectTypeCategory> {
    return {{"Languages",
             {ProjectType::Cpp, ProjectType::Python, ProjectType::JavaScript, ProjectType::Java,
              ProjectType::Go, ProjectType::Rust, ProjectType::CSharp, ProjectType::Ruby,
              ProjectType::PHP, ProjectType::Swift, ProjectType::Kotlin}},
            {"Build Systems",
             {ProjectType::CMake, ProjectType::Make, ProjectType::Vcpkg, ProjectType::Conan,
              ProjectType::Gradle, ProjectType::Maven}},
            {"Platforms", {ProjectType::macOS, ProjectType::Linux, ProjectType::Windows}},
            {"Editors", {ProjectType::VSCode, ProjectType::JetBrains, ProjectType::Vim}}};
}

// Helper: Check if build system is relevant for given languages
auto is_build_system_relevant(ProjectType build_system, const std::vector<ProjectType>& languages)
    -> bool {
    // If no languages selected, show all build systems
    if (languages.empty()) {
        return true;
    }

    // Define which build systems are relevant for which languages
    static const std::unordered_map<ProjectType, std::unordered_set<ProjectType>> relevance_map = {
        // C++ build systems
        {ProjectType::CMake, {ProjectType::Cpp}},
        {ProjectType::Make, {ProjectType::Cpp}},
        {ProjectType::Vcpkg, {ProjectType::Cpp}},
        {ProjectType::Conan, {ProjectType::Cpp}},

        // Java/Kotlin build systems
        {ProjectType::Gradle, {ProjectType::Java, ProjectType::Kotlin}},
        {ProjectType::Maven, {ProjectType::Java, ProjectType::Kotlin}},
    };

    auto it = relevance_map.find(build_system);
    if (it == relevance_map.end()) {
        // Not a build system, always show
        return true;
    }

    const auto& relevant_languages = it->second;

    // Check if any selected language is in the relevant set
    for (const auto& lang : languages) {
        if (relevant_languages.count(lang) > 0) {
            return true;
        }
    }

    return false;
}

} // namespace repo::ops
