#include <string_view>

namespace repo::ops::templates_internal {

constexpr std::string_view GITIGNORE_RUST = R"(# ===================================
# Rust
# ===================================

# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable
# Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these
*.pdb
)";

auto get_rust_template() -> std::string_view {
    return GITIGNORE_RUST;
}

} // namespace repo::ops::templates_internal
